spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    #        default_batch_fetch_size: 100
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: yonghyunkwon98@gmail.com
    password: pqoc lssl xvji xsmm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

logging.level:
  org.hibernate.SQL:

jwt:
  secret: Y2V2YXMtc3ByaW5nLWJvb3Qtand0LXlvbmdoeXVuLXNlY3JldC1qdW5nYW4tdGVjaC1zcHJpbmctYm9vdC1qd3QtYmFiby1zZWNyZXQK